name: Publish reusable workflow

on:
  workflow_call:
    inputs:
      with-update-package-lock:
        type: boolean
        default: false
      cmd:
        type: string
        default: "bootstrap"
        description: "Execute npm run cmd. For example cmd='bootstrap' => npm run bootstrap"
      commit-message:
        type: string
        default: 'chore: update package-locks [skip ci]'
    secrets:
      gh_token:
        required: true
      npm_registry_token:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.gh_token }}
      NPM_REGISTRY_TOKEN: ${{ secrets.npm_registry_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         show-progress: false

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Unset header
        # https://github.com/intuit/auto/issues/1030
        run: git config --local --unset http.https://github.com/.extraheader

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Lerna found changed packages
        id: lerna
        uses: ./.github/actions/lerna-changed

      - name: Create "HAS_CHANGED" shortcut
        run: echo "HAS_CHANGED=${{ steps.lerna.outputs.HAS_CHANGED }}" >> $GITHUB_ENV

      - name: Lerna bootstrap
        if: ${{ fromJSON(env.HAS_CHANGED) }}
        run: npm run ${{ inputs.cmd }}

      - name: API Report
        if: ${{ fromJSON(env.HAS_CHANGED) }}
        run: npm run api:report

      - name: Release Info
        if: ${{ fromJSON(env.HAS_CHANGED) }}
        run: npm whoami && npx lerna info && npx auto info || echo 'auto info returned 1'

      - name: Create Release
        if: ${{ fromJSON(env.HAS_CHANGED) }}
        run: npm run release

      - name: Update package-lock files
        if: ${{ fromJSON(env.HAS_CHANGED) && inputs.with-update-package-lock }}
        uses: ./.github/actions/update-package-lock
        with:
          commit-message: ${{ inputs.commit-message }}
          token: ${{ secrets.gh_token }}
