name: PR theme-builder

on:
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - dev

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  authorize:
    name: Authorize external pull request
    uses: ./.github/workflows/authorize-external-pr.yml

  build:
    needs: [authorize]
    uses: ./.github/workflows/theme-builder-common.yml
    secrets: inherit
